import { FC, useCallback, useMemo } from "react";
import styles from "./ResultsSummaryModal.module.scss";
import Modal from "./Modal";
import LoadingBar from "../LoadingBar/LoadingBar";
import { ResultContextObject } from "../../Utilities/llm";
import loadingIcon from '../../Assets/Images/Loading/loading-purple.png';
import CompleteIcon from '../../Icons/Buttons/Checkmark/Circle Checkmark.svg?react';

interface ResultsSummaryModalProps {
  isOpen?: boolean;
  isSummaryAvailable: boolean;
  isSummaryLoading: boolean;
  onClose?: Function;
  resultContext: ResultContextObject[];
  streamedText: string;
}

const ResultsSummaryModal: FC<ResultsSummaryModalProps> = ({isOpen = false, isSummaryAvailable, isSummaryLoading, onClose = ()=>{}, streamedText, resultContext}) => {

  const startOpen = (isOpen === undefined) ? false : isOpen;

  const handleMatchedNameClick = useCallback((match: ResultContextObject) => {
    console.log(match);
  }, []);

  const processedText = useMemo(() => {
    const names = resultContext.map((contextItem) => contextItem.name).join("|");
    const regex = new RegExp(`\\b(${names})\\b`, "gi");

    return streamedText.split("\n").map((paragraph, paraIndex) => {
      const processedParagraph = paragraph.split(regex).map((part, index) => {
        const match = resultContext.find(
          (contextItem) => contextItem.name.toLowerCase() === part.toLowerCase()
        );
        if (match) {
          return (
            <span
              key={`${paraIndex}-${index}`}
              onClick={() => handleMatchedNameClick(match)}
              className={styles.summaryMatch}
            >
              {match.name}
            </span>
          );
        }
        return part;
      });
      return <p key={paraIndex}>{processedParagraph}</p>;
    });
  }, [streamedText, resultContext, handleMatchedNameClick]);


  const handleClose = () => {
    onClose();
  }

  return (
    <Modal 
      isOpen={startOpen} 
      onClose={handleClose} 
      className={styles.summaryModal}
      containerClass={styles.summaryModalContainer}
      >
        <div className={styles.top}>
          <h5 className={styles.heading}>Results Summary</h5>
          <p className={styles.statusText}>Generated by AI {isSummaryLoading ? <img src={loadingIcon} className={`${styles.summaryLoadingIcon} loadingIcon`} alt="loading icon"/> : <CompleteIcon/> }</p>
        </div>
        <div className={styles.bottom}>
          <div className={`scrollable`}>
            <LoadingBar
              useIcon
              loadingText="Summarizing Results"
              disclaimerText={<p>Your summary is currently being generated.</p>}
              className={`${styles.loadingArea} ${isSummaryLoading && !streamedText ? styles.active : ""}`}
            />
            <>{processedText}</>
            {/* {
              !!processedText && 
              processedText.split('\n').map((line, index) => {
                return <p key={index}>{line}</p>
              }) 
            } */}
          </div>
        </div>
    </Modal>
  );
}


export default ResultsSummaryModal;

